var files = {
    "Fundamentals": [
        "001webgl-fundamentals",
        "002webgl-2d-rectangle",
        "003webgl-2d-rectangle-top-left",
        "004webgl-2d-rectangles",
        "005webgl-2d-triangle-with-position-for-color",
        "006webgl-2d-rectangle-with-2-colors",
        "007webgl-2d-rectangle-with-random-colors",
        "008webgl-2d-rectangle-with-2-byte-colors"
    ],
    "Image Processing": [
        "009webgl-2d-image",
        "webgl-2d-image-red2blue",
        "webgl-2d-image-blend",
        "webgl-2d-image-3x3-convolution",
        "webgl-2d-image-processing"
    ],
    "2D Translation,rotation,scale,matrix math": [
        "webgl-2d-rectangle-translate",
        "webgl-2d-geometry-translate-better",
        "webgl-2d-geometry-rotation",
        "webgl-2d-geometry-rotation-angle",
        "webgl-2d-geometry-scale",
        "webgl-2d-geometry-matrix-transform",
        "webgl-2d-geometry-matrix-transform-trs",
        "webgl-2d-geometry-matrix-transform-hierarchical",
        "webgl-2d-geometry-matrix-transform-center-f",
        "webgl-2d-geometry-matrix-transform-with-projection",
        "webgl-2d-geometry-matrix-transform-simpler-functions"
    ],
    "3D": [
        "webgl-3d-step1",
        "webgl-3d-step2",
        "webgl-3d-step3",
        "webgl-3d-step4",
        "webgl-3d-step5",
        "webgl-3d-step6",
        "webgl-3d-perspective",
        "webgl-3d-perspective-w",
        "webgl-3d-perspective-w-matrix",
        "webgl-3d-perspective-matrix",
        "webgl-3d-camera",
        "webgl-3d-camera-look-at",
        "webgl-3d-camera-look-at-heads"
    ],
    "Lighting": [
        "webgl-3d-lighting-directional",
        "webgl-3d-lighting-directional-world",
        "webgl-3d-lighting-directional-worldinversetranspose",
        "webgl-3d-lighting-point",
        "webgl-3d-lighting-point-specular-power",
        "webgl-3d-lighting-point-color",
        "webgl-3d-lighting-spot",
        "webgl-3d-lighting-spot-falloff",
        "webgl-3d-lighting-spot-falloff-using-smoothstep"
    ],
    "Structure and Organization": [
        "webgl-less-code-more-fun",
        "webgl-less-code-more-fun-triangle",
        "webgl-less-code-more-fun-quad",
        "webgl-less-code-more-fun-quad-guess",
        "webgl-less-code-more-fun-quad-programinfo",
        "webgl-multiple-objects-manual",
        "webgl-multiple-objects-list",
        "webgl-multiple-objects-list-optimized",
        "webgl-scene-graph-solar-system",
        "webgl-scene-graph-solar-system-larger-earth",
        "webgl-scene-graph-solar-system-larger-earth-fixed",
        "webgl-scene-graph-solar-system-adjusted",
        "webgl-scene-graph-block-guy"
    ],
    "Geometry":[
        "webgl-3d-lathe-step-01",
        "webgl-3d-lathe-step-02",
        "webgl-3d-lathe-step-03"
    ],
    "Textures":[
        "webgl-3d-textures",
        "webgl-3d-textures-texture-coords-mapped",
        "webgl-3d-textures-repeat-clamp",
        "webgl-3d-textures-mips",
        "webgl-3d-textures-mips-tri-linear",
        "webgl-3d-textures-good-npot",
        "webgl-3d-textures-texture-atlas",
        "webgl-data-texture-3x2",
        "webgl-2-textures",
        "webgl-cors-permission-good",
        "webgl-clipspace-rectangles",
        "webgl-clipspace-rectangles-with-varying",
        "webgl-clipspace-rectangles-with-varying-non-1-w",
        "webgl-clipspace-rectangles-with-varying-non-1-w-repeat",
        "webgl-perspective-correct-cube",
        "webgl-non-perspective-correct-cube"
    ],
    "Rendering To A Texture":[
        "webgl-render-to-texture",
        "webgl-render-to-texture-3-cubes-no-depth-buffer",
        "webgl-render-to-texture-3-cubes-with-depth-buffer"
    ]
}